version: "3"                                             
                                                         
services:                                                
  mongo:                                                 
    image: mongo                                         
    container_name: mongo_dashboard                      
    volumes:                                             
      - /home/azure/mongodata:/data/db                   
    ports:                                               
      - "27017:27017"                                    
    networks:                                            
      - mynetwork
  eurekaserver:                                    
    image: mauriziopinzi/eurekaserver              
    container_name: eurekaserver                   
    ports:                                               
      - "8761:8761"                                      
    networks:                                            
      - mynetwork
  restservicedashboard1:                                    
    image: mauriziopinzi/restservicedashboard              
    container_name: restservicedashboard1                   
    ports:                                               
      - "8090:8090"                                      
    networks:                                            
      - mynetwork
    depends_on:
      - "mongo"
  schedulerdashboard:                                    
    image: mauriziopinzi/schedulerdashboard              
    container_name: schedulerdashboard                   
    ports:                                               
      - "8093:8093"                                      
    networks:                                            
      - mynetwork
    depends_on:
      - "mongo"
  nginx_load:                                    
    image: nginx              
    container_name: nginx_load
    volumes:                                             
      - /home/azure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:                                               
      - "8089:80"                                      
    networks:                                            
      - mynetwork
    depends_on:
      - "mongo"
                                                         
networks:                                                
  mynetwork:                                             